name: 'Code Reviewer'
description: 'Reviews code in pull requests to ensure they meet standards not checkable with unit tests or linters'

inputs:
  token:
    required: true
    description: 'GitHub access token with repo permissions'
  changelog:
    required: false
    default: 'true'
    description: 'Whether to check the changelog for missing entries'
  todos:
    required: false
    default: 'true'
    description: 'Whether to check for TODOs in code that are resolved by the current PR'

runs:
  using: 'composite'
  steps:
    - name: Get Story Numbers
      id: stories
      if: ${{ inputs.changelog }} = 'true'
      uses: Renddslow/prepare-branch-commit@v1.0.1
      with:
        branch-name: ${{ github.head_ref }}
    - name: Get TODOs
      id: todos
      if: ${{ inputs.changelog }} = 'true'
      # Find all comments with matching story numbers
      # Results concatenated with ':::' to support single line requirement
      run: |
        echo "::set-output name=todo-files::$(echo "${{ steps.stories.outputs.issue-tags }}" | tr ',' '\n' | xargs -I {} sh -c "grep -n '.*\bTODO.*{}' -R . --exclude-dir 'node_modules' || true" | awk '{print}' ORS='_:::_')"
      shell: bash
    - name: Code Review
      run: node ${{ github.action_path }}/bin/index.js
      shell: bash
      env:
        BASE_DIR: ${{ github.workflow_root }}
        CODE_REVIEW_CHANGELOG: ${{ inputs.changelog }}
        CODE_REVIEW_TODOS: ${{ inputs.todos }}
        CODE_REVIEW_TOKEN: ${{ inputs.token }}
        PR_BRANCH: ${{ github.head_ref }}
        STORY_NUMBERS: ${{ steps.stories.outputs.issue-tags }}
        TODO_COMMENTS: ${{ steps.todos.outputs.todo-files }}
